version: "3"
services:
  score-app:
    image: score:1.0.0
    environment:
    - DB_HOSTNAME=score-database
    - DB_PORT=5432
    - DB_USERNAME=score
    - DB_PASSWORD=score
    - DB_NAME=score
    - DS_URL=https://datastudio.google.com/s/lygI5Phd6mc
    - GOOGLE_APPLICATION_CREDENTIALS=service-account.json
    - GIN_MODE=release
    ports:
      - "80:8080"
    depends_on:
      score-database:
        condition: service_healthy
  score-database:
    image: postgres:12.10-alpine3.15
    container_name: "score-database"
    volumes:
      - ./volume/score-database/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=score
      - POSTGRES_PASSWORD=score
      - POSTGRES_DB=score
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5