version: "3"
services:
  scstore-app:
    image: scstore:1.0.0
    environment:
      - DB_HOSTNAME=scstore-database
      - DB_PORT=5432
      - DB_USERNAME=scstore
      - DB_PASSWORD=scstore
      - DB_NAME=scstore
      - GIN_MODE=release
    ports:
      - "80:8080"
    depends_on:
      scstore-database:
        condition: service_healthy
  scstore-database:
    image: postgres:14.2
    container_name: "scstore-database"
    environment:
      - POSTGRES_USER=scstore
      - POSTGRES_PASSWORD=scstore
      - POSTGRES_DB=scstore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5